core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    SubcategoryView,
    privacypolicy,
    termsandconditions,
    PickupView,
    order_success,
    contact,
    about
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-success/', order_success, name='order-success'),
    path('pickup/', PickupView.as_view(), name='pickup'),  # Add this line
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('subcategory/<slug>/', SubcategoryView.as_view(), name='subcategory'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path("privacypolicy/", privacypolicy, name="privacy-policy"),
    path("termsandconditions/", termsandconditions, name="terms-and-conditions"),
    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% load category_template_tags %}
{% block content %}
<style type="text/css">
	.selection-2{
	display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
	}
</style>

	<!-- Title Page -->
	<section class=" bg-title-page p-t-50 p-b-40 flex-col-c-m" style="background-image: url(/media/{{ category_image }});">
		<h2 class="l-text2 t-center" style="color: white;text-shadow: 0px 10px 1px #000;-webkit-text-stroke: #000 1px;">
			{{ category_title }}
		</h2>
		<p class="m-text13 t-center" style="font-family: cursive; font-weight:bold; font-size: 25px; -webkit-text-stroke: #000 0.5px;">
			{{ category_description }}
		</p>
	</section>


	<!-- Content page -->
	<section class="bgblack p-t-55 p-b-65">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
					<div class="leftbar  p-r-0-sm" style="border: 5px solid #000; padding:10%; box-shadow: -30px 15px 1px lightgreen;border:1px solid #fff">
						<!--  -->
						<h4 class="m-text14 p-b-7">
							Categories
						</h4>

						<ul class="p-b-54">
							<li class="p-t-4">
								<a href="/shop" class="s-text13 active1">
									All
								</a>
							</li>

							{% categories_li_a %}

						</ul>

						<h4 class="m-text14 p-b-7">
							Subcategories
						</h4>
						
						<ul class="p-b-54">
							{% for subcategory in subcategories %}
							<li class="p-t-4">
								<a href="{% url 'core:subcategory' slug=subcategory.slug %}" class="s-text13 ">
									{{ subcategory.title }}
								</a>
							</li>
							{% endfor %}
						</ul>
						

						



						{% comment %} <!--  -->
						<h4 class="m-text14 p-b-32">
							Filters
						</h4>

						<div class="filter-price p-t-22 p-b-50 bo3">
							<div class="m-text15 p-b-17">
								Price
							</div>

							<div class="wra-filter-bar">
								<div id="filter-bar"></div>
							</div>

							<div class="flex-sb-m flex-w p-t-16">
								<div class="w-size11">
									<!-- Button -->
									<button class="flex-c-m size4 bg7 bo-rad-15 hov1 s-text14 trans-0-4">
										Filter
									</button>
								</div>

								<div class="s-text3 p-t-10 p-b-10">
									Range: $<span id="value-lower">610</span> - $<span id="value-upper">980</span>
								</div>
							</div>
						</div>

						<div class="filter-color p-t-22 p-b-50 bo3">
							<div class="m-text15 p-b-12">
								Color
							</div>

							<ul class="flex-w">
								<li class="m-r-10">
									<input class="checkbox-color-filter" id="color-filter1" type="checkbox" name="color-filter1">
									<label class="color-filter color-filter1" for="color-filter1"></label>
								</li>

								<li class="m-r-10">
									<input class="checkbox-color-filter" id="color-filter2" type="checkbox" name="color-filter2">
									<label class="color-filter color-filter2" for="color-filter2"></label>
								</li>

								<li class="m-r-10">
									<input class="checkbox-color-filter" id="color-filter3" type="checkbox" name="color-filter3">
									<label class="color-filter color-filter3" for="color-filter3"></label>
								</li>

								<li class="m-r-10">
									<input class="checkbox-color-filter" id="color-filter4" type="checkbox" name="color-filter4">
									<label class="color-filter color-filter4" for="color-filter4"></label>
								</li>

								<li class="m-r-10">
									<input class="checkbox-color-filter" id="color-filter5" type="checkbox" name="color-filter5">
									<label class="color-filter color-filter5" for="color-filter5"></label>
								</li>

								<li class="m-r-10">
									<input class="checkbox-color-filter" id="color-filter6" type="checkbox" name="color-filter6">
									<label class="color-filter color-filter6" for="color-filter6"></label>
								</li>

								<li class="m-r-10">
									<input class="checkbox-color-filter" id="color-filter7" type="checkbox" name="color-filter7">
									<label class="color-filter color-filter7" for="color-filter7"></label>
								</li>
							</ul>
						</div>

						<div class="search-product pos-relative bo4 of-hidden">
							<input class="s-text7 size6 p-l-23 p-r-50" type="text" name="search-product" placeholder="Search Products...">

							<button class="flex-c-m size5 ab-r-m color2 color0-hov trans-0-4">
								<i class="fs-12 fa fa-search" aria-hidden="true"></i>
							</button>
						</div> {% endcomment %}
					</div>
				</div>

				<div class="col-sm-6 col-md-8 col-lg-9 p-b-50">
					<!--  -->
					{% comment %} <div class="flex-sb-m flex-w p-b-35">
						<div class="flex-w">
						
							<div class="rs2-select2 bo4 of-hidden w-size12 m-t-5 m-b-5 m-r-10" >
								<select class="selection-2" name="sorting">
									<option>Default Sorting</option>
									<option>Popularity</option>
									<option>Price: low to high</option>
									<option>Price: high to low</option>
								</select>
							</div>

							<div class="rs2-select2 bo4 of-hidden w-size12 m-t-5 m-b-5 m-r-10">
								<select class="selection-2" name="sorting">
									<option>Price</option>
									<option>$0.00 - $50.00</option>
									<option>$50.00 - $100.00</option>
									<option>$100.00 - $150.00</option>
									<option>$150.00 - $200.00</option>
									<option>$200.00+</option>

								</select>
							</div>
						</div>

						<span class="s-text8 p-t-5 p-b-5">
							Showing 1–12 of 16 results
						</span>
					</div> {% endcomment %}

					<!-- Product -->
					<div class="row">
						{% for item in object_list %}
							<div class="col-sm-12 col-md-6 col-lg-4 p-b-50" >
								<!-- Block2 -->
								<div class="block2" style="box-shadow: 0px 10px 20px #90EE90;padding: 5%;border: 1px solid #e0d9d9; border-radius: 2%;">
									<a href="{{ item.get_absolute_url }}">
										<div class="block2-img wrap-pic-w of-hidden pos-relative">
											<img src="{{ item.item_image1.url }}" alt="IMG-PRODUCT" style="height: auto; width:100%">
										</div>
									</a>

									<div class="block2-txt p-t-20">
										<a href="{{ item.get_absolute_url }}" class="block2-name dis-block s-text3 p-b-5">
											{{ item.title }}
										</a>
										<a href="{{ item.get_absolute_url }}" class="block2-name dis-block s-text3 p-b-5" style=" color:#888888;    font-size: 15px;">
											{{ item.item_details }}
										</a>
									</div>
								</div>
							</div>
						{% endfor %}

						

						
				
				</div>
			

				<br>
				{% if object_list.has_other_pages %}
<div class="pagination flex-m flex-w p-t-26">
    {% if object_list.has_previous %}
    <a class="page-link" href="?page=1" aria-label="First">
        <span aria-hidden="true">&laquo;&laquo;</span>
        <span class="sr-only">First</span>
    </a>
    <a class="page-link" href="?page={{ object_list.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
    </a>
    {% endif %}
    
    {% for num in object_list.paginator.page_range %}
        {% if object_list.number == num %}
            <a href="?page={{ num }}" class="item-pagination flex-c-m trans-0-4 active-pagination">{{ num }}</a>
        {% elif num > object_list.number|add:'-3' and num < object_list.number|add:'3' %}
            <a href="?page={{ num }}" class="item-pagination flex-c-m trans-0-4">{{ num }}</a>
        {% endif %}
    {% endfor %}
    
    {% if object_list.has_next %}
    <a class="page-link" href="?page={{ object_list.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
    </a>
    <a class="page-link" href="?page={{ object_list.paginator.num_pages }}" aria-label="Last">
        <span aria-hidden="true">&raquo;&raquo;</span>
        <span class="sr-only">Last</span>
    </a>
    {% endif %}
</div>
{% endif %}

			</div>
		</div>
	</section>


		{% endblock content %}

templates/nav.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}

<style>
	.topbar {
		background: linear-gradient(to left, red, #75ffaa,#fff,lightgrey ,#6630fc); /* Replace with your desired background colors */
		height: 10vh;
	
	}
	a{
		font-family:cursive;
	}
	.main_menu > li > a{
		font-family:cursive;
	}
	
</style>
<!-- Header -->
<header class="header1">
		<!-- Header desktop -->
		<div class="container-menu-header">
			 <div class="topbar">

				

				<div class="topbar-child2">
					 <span class="topbar-email" >
						<a href="/" style="">
						   Home
						</a>
					</span> 
				</div>
				<div class="topbar-child2">
					<span class="topbar-email" >
					   <a href="/shop/" style="">
						  Shop
					   </a>
				   </span> 
			   </div>
{% comment %} 
			   <div class="topbar-child2">
				<span class="topbar-email" >
				   <a href="/contact/" style="">
					  Contact Us
					</a>
					</span> 
				</div> {% endcomment %}
				<div class="topbar-child2">
					<span class="topbar-email" >
						<a href="/about/" style="">
							About Us
						</a>
					</span> 
				</div>
			</div> 

			<div class="wrap_header">
				<!-- Logo -->
				<a href="/" class="logo">
					<img src="{% static 'images/logo3.png' %}" alt="logo" >
				</a>

				<!-- Menu -->
				<div class="wrap_menu">
					<nav class="menu">
						<ul class="main_menu">
							{% comment %} <li>
								<a href="/">Home</a>

							</li>

							<li>
								<a href="/shop/">Shop</a>
							</li> {% endcomment %}

							{% categories %}

							{% if request.user.is_authenticated %}
							<li>
								<div class="header-wrapicon2">
								<a href="{% url 'core:order-summary' %}">
									
									<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">{{ request.user|cart_item_count }}</span>
									</a>
								</div>
							</li>
							<li>
								<a href="{% url 'account_logout' %}">Logout</a>
							</li>
							{% else %}
							<li>
								<a href="#">Login</a>
								<ul class="sub_menu">
									<li><a href="{% url 'account_login' %}">Login</a></li>
									<li><a href="{% url 'account_signup' %}">SignUp</a></li>
								</ul>
							</li>
							{% endif %}
						</ul>
					</nav>
				</div>

				
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap_header_mobile">
		 <!-- Logo moblie -->
			<a href="/" class="logo-mobile">
				<img src="{% static 'images/logo3.png' %}" alt="IMG-LOGO">
			</a>

		  <!-- Button show menu -->
			<div class="btn-show-menu">
				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">
					<a href="#" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide2"></span>

					<div class="header-wrapicon2">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">0</span>

						<!-- Header cart noti -->
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">
								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											White Shirt With Pleat Detail Back
										</a>

										<span class="header-cart-item-info">
											1 x $19.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Converse All Star Hi Black Canvas
										</a>

										<span class="header-cart-item-info">
											1 x $39.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Nixon Porter Leather Watch In Tan
										</a>

										<span class="header-cart-item-info">
											1 x $17.00
										</span>
									</div>
								</li>
							</ul>

							<div class="header-cart-total">
								Total: $75.00
							</div>

							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="cart.html" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										View Cart
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="#" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										Check Out
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div> 
		</div>

	<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">
					{% comment %} <li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<span class="topbar-child1">
							Free shipping for standard order over $100
						</span>
					</li>

					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">
							<span class="topbar-email">
								fashe@example.com
							</span>

							<div class="topbar-language rs1-select2">
								<select class="selection-1" name="time">
									<option>USD</option>
									<option>EUR</option>
								</select>
							</div>
						</div>
					</li> {% endcomment %}

					{% comment %} <li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile">
							<a href="#" class="topbar-social-item fa fa-facebook"></a>
							<a href="#" class="topbar-social-item fa fa-instagram"></a>
							<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
							<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
							<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
						</div>
					</li> {% endcomment %}

					<li class="item-menu-mobile">
						<a href="/">Home</a>
					</li>
					<li class="item-menu-mobile">
						<a href="/about/">About Us</a>
					</li>

					<li class="item-menu-mobile">
						<a href="/shop">Shop</a>
					</li>

					{% categories_mobile %}

					{% if request.user.is_authenticated %}
					<li class="item-menu-mobile">
						<a href="{% url 'core:order-summary' %}">Cart<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
					</li>
					<li class="item-menu-mobile">
						<a href="{% url 'account_logout' %}">Logout</a>
					</li>
					{% else %}
					<li class="item-menu-mobile">
						<a href="#">Login</a>
						<ul class="sub-menu">
							<li><a href="{% url 'account_login' %}">Login</a></li>
							<li><a href="{% url 'account_signup' %}">SignUp</a></li>
						</ul>
						<i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
					</li>
					{% endif %}

				</ul>
			</nav>
		</div> 
	</header>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<div class="floating_btn">
  <a class="icon-whatsapp" target="_blank" href="https://wa.me/923215435737">
    <div class="whatsapp-contact_icon">
      <i class="fa fa-whatsapp my-float"></i>
    </div>
  </a>

</div>

  <style>

.icon-whatsapp{
  text-decoration:none;
}
.floating_btn {
  position: fixed;
  bottom: 30px;
  /*right: 30px;*/
  width: 100px;
  height: 100px;
  display: flex;
  flex-direction: column;
  align-items:center;
  justify-content:center;
  z-index: 1000;
}

@keyframes pulsing {
  to {
    box-shadow: 0 0 0 30px rgba(232, 76, 61, 0);
  }
}

.whatsapp-contact_icon {
  background-color: #42db87;
  color: #fff;
  width: 60px;
  height: 60px;
  font-size:30px;
  border-radius: 50px;
  text-align: center;
  box-shadow: 2px 2px 3px #999;
  display: flex;
  align-items: center;
  justify-content: center;
  transform: translatey(0px);
  animation: pulse 1.5s infinite;
  box-shadow: 0 0 0 0 #42db87;
  -webkit-animation: pulsing 1.25s infinite cubic-bezier(0.66, 0, 0, 1);
  -moz-animation: pulsing 1.25s infinite cubic-bezier(0.66, 0, 0, 1);
  -ms-animation: pulsing 1.25s infinite cubic-bezier(0.66, 0, 0, 1);
  animation: pulsing 1.25s infinite cubic-bezier(0.66, 0, 0, 1);
  font-weight: normal;
  font-family: sans-serif;
  text-decoration: none !important;
  transition: all 300ms ease-in-out;
  left:40%;
  position: relative;
}


.whatsapp-text_icon {
  margin-top: 8px;
  color: #000;
  font-size: 13px;
  width:10em;
  background-color: rgba(13, 208, 91, 0.6);
  border:1px solid #ccc;
  left:25%;
  padding-left:3%;
  position: relative;
  box-shadow:0px 0px 5px #000;
}
  </style>

templates/order_snippet.html
   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
.text-muted{
  font-family: cursive;
}
.my-0{
  font-family: cursive;
}
.list-group-item{
  border: 1px solid #000;
}
.badge{
  font-family: math;
  background-color: #000000;
}
.btn-secondary{
  background: black;
  font-family: cursive;
}
.form-control{
  border: 1px solid #000 !important;
}
.dio{
  border: 1px solid #000 !important;
}
    </style>
  
 
    

   

    <div class="col-md-4 order-md-2 mb-4" style="background: #fff;padding:2%">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted"></small>
          </div>
          {% comment %} <span class="text-muted">${{ order_item.get_final_price }}</span> {% endcomment %}
          <span class="text-muted">Quantity : {{ order_item.quantity }}</span>
        </li>
        {% endfor %}
        {% comment %} <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{order.coupon.code}}</small>
          </div>
          <span class="text-success">-${{ order.coupon.amount }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong>${{ order.get_total }}</strong>
        </li> {% endcomment %}
      </ul>
      
      {% if DISPLAY_COUPON_FORM %}
      <form method="POST" action="{% url 'core:add-coupon' %}" class="dio card p-2">
        {% csrf_token %}
        <div class="input-group">
          {{ couponform.code }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>

  

templates/order_summary.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
<style>
  .alert-info{
    margin-top: 6%;
    color: #888888;
    background: linear-gradient(252deg, black, transparent);
  }
  .uio{
    margin-top: 9%;
    margin-bottom: 5%;
    padding: 2%;
    box-shadow: 0px 0px 5px #000;
  }
  .yahu{
    font-family: fangsong;
    text-shadow: 5px 5px 5px grey;
    padding-bottom: 2%;
  }
  .oi{
    color: #000;
    font-family: cursive;
    font-size: 18px;
  }
  .io{
    font-family: math;
  }
  .btn-primary{
    background: radial-gradient(#fffbfb7a, #59ff747d);
    color: #000;
    border: 0.5px solid #59ff747d;
  }
  .btn-warning{
    background: linear-gradient(199deg, black, transparent);
    border: none;
    color: #fff;
  }
  @media (max-width: 767.98px) {
    .table thead {
      display: none;
    }
    .table, .table tbody, .table tr, .table td {
      display: block;
      width: 100%;
    }
    .table td {
      text-align: right;
      padding-left: 50%;
      position: relative;
    }
    .table td::before {
      content: attr(data-label);
      position: absolute;
      left: 0;
      width: 50%;
      padding-left: 15px;
      font-weight: bold;
      text-align: left;
    }
    .oi {
      font-size: 14px;
    }
  }
</style>

<div class="uio container">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="yahu">Order Summary</h2>
      <table class="table">
        <thead>
          <tr>
            <th class="io" scope="col">#</th>
            <th class="io" scope="col">Product Image</th>
            <th class="io" scope="col">Product Name</th>
            <th class="io" scope="col">Product Price</th>
            <th class="io" scope="col">Total Price</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
			<img src="{{ order_item.item.item_image1.url }}" style="width: 130px;"> 
            </td>
            <td class="oi">{{ order_item.item.title }}</td>
            <td class="oi">{{ order_item.item.price }}</td>
            <td>
            	<a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-3"></i></a>
            	{{ order_item.quantity }}
            	<a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-3"></i></a>
            </td>
            <td>
              {% comment %} {% if order_item.item.discount_price %}
                  ${{ order_item.get_total_discount_item_price}}
                  <span class="badge badge-primary">  Saving ${{ order_item.get_amount_saved }}</span>
              {% else %}
                  ${{ order_item.get_total_item_price}}
              {% endif %} {% endcomment %}
              <a style="color: red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
              	<i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
			<td colspan="5">Your cart is empty</td>
          </tr>
        </tbody>
        {% endfor %}
        {% comment %} {% if object.coupon %}
        <tr>
          <td colspan="5"><b>Coupon : </b></td>
          <td>- ${{ object.coupon.amount }}</td>
        </tr>
        {% endif%}  {% endcomment %}

        {% comment %} <tr>
        	<td colspan="5"><b>Order Total : </b></td>
        	<td><b>${{ object.get_total }}</b></td>
        </tr> {% endcomment %}
        <tr>
        	<td colspan="5">
        		<a href="/checkout" class="btn btn-warning float-right ml-2">Checkout</a>
        		<a href="/" class="btn btn-primary float-right">Continue Shopping</a>

        	</td>
        </tr>

      </table>
    </div>
  </div>
</div>

{% endblock content %}

templates/request_refund.html
{% extends 'base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block content %}


<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-3 mt-3">
      <h2>Request Refund</h2>
      <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
     
    </div>
  </div>
</div>

{% endblock content %}